run: test.cc ../declarations.cc ../expressions.cc ../external_definitions.cc ../statements.cc ../../lexer/lexer.cc ../../lexer/token.cc ../../util/print_info.cc ../declarators.cc
	g++ -std=c++17 -g ../declarators.cc ../declarations.cc ../expressions.cc ../external_definitions.cc ../statements.cc ../../lexer/lexer.cc ../../lexer/token.cc ./test.cc ../../util/print_info.cc -o test
